name: ensemble_walletconnect
description: Open protocol for connecting decentralized applications to mobile wallets with QR code scanning or deep linking.
version: 1.0.0
homepage: https://walletconnect.org/
repository: https://github.com/EnsembleUI/ensemble_walletconnect
issue_tracker: https://github.com/EnsembleUI/ensemble_walletconnect/issues

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  # WebSocket Channel
  web_socket_channel: ^2.1.0

  # UUID
  uuid: ^4.5.1

  # Cryptography
  cryptography: ^2.0.5

  # Hex
  convert: ^3.0.1

  # JSON Annotation
  json_annotation: ^4.4.0

  # Stack trace
  stack_trace: ^1.10.0

dev_dependencies:
  # Testing framework
  test: ^1.20.1

  # JSON Serialization
  json_serializable: ^6.1.4

  # Build runner
  build_runner: ^2.1.7

# Topics help users discover your package
topics:
  - walletconnect
  - web3
  - dapp
  - blockchain
  - crypto
  - ethereum
  - algorand
